select '## ## Creating tables' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/CAPSTONE_TABLE_CREATION.sql;
select '## ## Loading vendors' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/Load_vendor.sql; 
select '## ## Loading types' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/Load_type.sql;
select '## ## Loading orders' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/Load_order.sql;
select '## ## Loading refunds' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/Load_refund.sql;
select '## ## Loading transactions' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/Load_Transaction.sql;
select '## ## Loading items' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/Load_Item.sql;
select '## ## Loading comics' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/Load_comic.sql;
select '## ## Loading order items' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/Load_OrderItem.sql;
select '## ## Loading transaction items' as '';
source C:/Users/749295/Documents/GitHub/Capstone-Project/Database/Load_transactionItem.sql;
